language: node_js
node_js: node
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
deploy:
  provider: heroku
  api_key:
    secure: ar+RXQd90WFafAsCnorb5UHIvb1n84i1a10Zy5LHsnscnD+0tz0XQ3DuIDKzC6wKATwn/hbYU6q7BH5zI0khZhz15m2YjTmJcBWaHMafCNbVD3h+N5a4ROwHzC28NFZQaOYZtDqqQMeRJCq5lcO8HQIzgPFMiS07ZmFa+gGwNRKaf6BlPXbupodsI6Ycopp2PLVTP8s/bDPZm++GoaAp4Aghi04i6bK2jjLMwJr8E0CYAr/R5RuMMRi53KtNtBPF+ZEanXviN6//OwRjfBOXTu4WFTvDdxNyyDOM17AzTjOxVpGkDqxcqcx5q55EXOMV1xvsQ/0sBNFEsjvEVdtmkPgR7gkEa8sy/5SwHRXf9cRjjthi3Hqj4h9yV9FBHtInR2sbvUsBfg4YOcj7nb2a1I5FyGz1Nlun7MZAV3GhtK2AewQr8H1dXC5O5NuLwtxM24b913zSHO1pbt99QW/ahCDFZzsnD5zCtIcPooD4T5YqlHR9OXF00NOLcSyzTluTj5372o7nhuGgO4tixrVCogtYx0dtFEbvqBEq7sUhso6fdDknZ3gp/aij2Djt5N1I4v0xBE15dbD0KWptvzfRW9wT1z+RwL5UofLHtIMaHAH5bALgzwr+IVD+wPZwuu0bvuooz7ieySTMtRZ53bVHhBf1jbWxS8fpqf8OVGVIhOc=
  app: radiant-peak-89382
  on:
    repo: jberthiaume1138/comic-collector
