language: node_js
node_js: node
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
deploy:
  provider: heroku
  api_key:
    secure: Fg8v0EM5r2gv3VEGY1J3fH9n6JWiv3NLCgeUOmdYQoVdLAIHmz+M6YjFtlGTZ3notWn+QzjfQTjrQlgraS0LS8sH44ihEzx0A3x7IxzkhBt7sU833lAcqCZGZlehshxL6hT8OfAwuaxtHxtlCoUEcpOaEbQ4ZWTZhldWWjZfRquIYjbtP0AzNA/A+h1MVhBJ8VEtGwlfEud89zaPpr2uJwwnHyIIFL7UHF5xK85lS1YCQCWEJSHvdLV4JCG/D8ibq13y+KXH1cz02f+IBd2vYY9Whwbb5HESHOSb7MHvLsbngLJtse2ITcSDoWbWTz7BKP6uYg6Dc4Bx0Issle7tGVRkPXG+CmoX6ZW6QJOHDDYuENJ4e0Lqet+YEFd0ecN31XMfTTH3G88Q3g0bjI4d9pMjBFbgku3iLVdFkPA1deeY5KJO728A2KbTIzITa4b67IOMn1pWPlmdMJ6cXZvFJVJSCS6X4AXrF92r+bSyOyvY9G4KVdgVLS2drN24raft6I1ci0U0oKzgic4jXE4/TSowRWYjYu5RyVD1WEYbgTt8etZ++e8UpZgCIyRLO7L/64ysKYAPpmBYLS6Sp2vZFrGQQl3BdC2Mf1ltlo+Znyn/+qxhFKjCZJoh8dTGtwKAeHBHlXBdRxWv5NAvT9wybI5nwXqntG86PiG/eRbaHGQ=
  app: radiant-peak-89382
  on:
    repo: jberthiaume1138/comic-collector
