language: node_js
node_js: node
services:
- mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server
deploy:
  provider: heroku
  api_key:
    secure: njPUa9qFnu3wAhMtoPw2akSzmS5uO7cKSeasfaD6aA3gTqjV6Isw9kDICz/CAuPTtC1fAeVjThbjvtJW6ytjLkSbOdSsCgRReuhFmnWGdLSI6SyABWMbvuSc3JJyR6aa3Ad4YGecjiaNZOa1ofJLpVY6OIQrwzkkumyxIkWpELsQC9Oi0jYhp5lVEBFNW5lEEGVQQS0HeaHIYzZ2vrD0yrIh934TnysYeX6YW8nMr0GrP5XcjQRC+JKapYRtYeT0ng8zSdBOlXdZLCh4V7m4SLGFffZWP0FPhxc3BVp+enSGbz/mUHhMmUDV+654NIY6j8rSfDbk/csu07r5dBKjgNFv/CR00j6A5tWFgt7NUq6H3ehe7a1Q17P9uSMeKcOVLkl+saiLMe2d+Qunc0Ud4pmSWw68e+HljJvJhUBw3OZU8/UjtzON+G2qs7tnM+1iLMi9zG65qqgLM73bnV4rn2RY6mIEA3q5K0k08kURReydQhVq2QpRpf+TMlZZfTizJaLiWS8kDXffRnVODP/hv+3ULvYZYjo/nVdvYhSldaYpY1YNo6caLepIDdFhmtMiVWzPexZsNvfEwBXbo+E+ULt4l1tLjFhmV35VOBJNdqLPqrI1qIj6fMRvVxFGt6DsbEEwb6Uu/JSXV448+C+UOvRR/L8gvTEu5OEGxXQPaG4=
  app: radiant-peak-89382
  on:
    repo: jberthiaume1138/comic-collector
